#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
export

source ${OPENSHIFT_APP_DIR}virtenv/bin/activate
export PYTHON_EGG_CACHE=${OPENSHIFT_APP_DIR}virtenv/lib/python2.6/site-packages
env
which python

if [ ! -f $OPENSHIFT_DATA_DIR/sqlite3.db ]
then
    echo "Copying ${OPENSHIFT_REPO_DIR}wsgi/mycms/sqlite3.db to $OPENSHIFT_DATA_DIR"
    cp ${OPENSHIFT_REPO_DIR}wsgi/mycms/sqlite3.db $OPENSHIFT_DATA_DIR/
else
    echo "Executing 'python ${OPENSHIFT_REPO_DIR}wsgi/mycms/manage.py syncdb --noinput'"
    python ${OPENSHIFT_REPO_DIR}wsgi/mycms/manage.py syncdb --noinput

    echo "Executing 'python ${OPENSHIFT_REPO_DIR}wsgi/mycms/manage.py migrate'"
    python ${OPENSHIFT_REPO_DIR}wsgi/mycms/manage.py migrate
fi

echo "Executing 'python ${OPENSHIFT_REPO_DIR}wsgi/mycms/manage.py collectstatic --noinput'"
python ${OPENSHIFT_REPO_DIR}wsgi/mycms/manage.py collectstatic --noinput